on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
          node-version: '18.x'
    - name: npm install
      run: |
        npm install

    - name: npm build
      run: npm build --if-present